"""LightGBM training script for retail demand forecasting.

Usage:
    python services/forecast-api/training/train.py
    python services/forecast-api/training/train.py --use-optuna --register-as-staging

Expects:
    data/train.csv          — Kaggle Store Sales dataset at the repo root.
    data/demand_features.parquet — generated by: python feature_repo/features.py

Outputs:
    model.pkl       — joblib-serialised dict {"model": lgbm, "encoder": ohe}
                      written to the current working directory.
    mlflow/         — MLflow tracking DB + artifacts (sqlite:///mlflow/mlflow.db)
"""

from __future__ import annotations

import logging
import os
import sys

import joblib
import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error

import mlflow
from mlflow import MlflowClient

# Ensure the service root is on sys.path so features.py is importable.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_SERVICE_DIR = os.path.dirname(_THIS_DIR)
if _SERVICE_DIR not in sys.path:
    sys.path.insert(0, _SERVICE_DIR)

from training.features import encode_categoricals  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s — %(message)s")
logger = logging.getLogger(__name__)

RANDOM_SEED = 42
TRAIN_RATIO = 0.8
MODEL_PARAMS = {
    "objective": "regression",
    "metric": "rmse",
    "num_leaves": 31,
    "n_estimators": 500,
    "random_state": RANDOM_SEED,
    "n_jobs": -1,
    "verbose": -1,
}
_REPO_ROOT = os.path.dirname(os.path.dirname(_SERVICE_DIR))
DEFAULT_DATA_PATH = os.path.join(_REPO_ROOT, "data", "train.csv")
OUTPUT_MODEL_PATH = "model.pkl"
MLFLOW_TRACKING_URI = "sqlite:///mlflow/mlflow.db"
EXPERIMENT_NAME = "mlops-loop-forecast"
MODEL_REGISTRY_NAME = "mlops-loop-forecast"


def load_data(path: str) -> pd.DataFrame:
    logger.info("Loading data from '%s'", path)
    df = pd.read_csv(path, parse_dates=["date"])
    required = {"date", "store_nbr", "family", "onpromotion", "sales"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    logger.info("Loaded %d rows", len(df))
    return df


def build_features_feast(
    df_raw: pd.DataFrame,
) -> tuple[pd.DataFrame, object, np.ndarray]:
    """Retrieve features via Feast offline store, then apply OHE.

    Requires: data/demand_features.parquet exists (run `python feature_repo/features.py` first).
    """
    from feast import FeatureStore

    repo_path = os.path.join(_REPO_ROOT, "feature_repo")
    store = FeatureStore(repo_path=repo_path)

    entity_df = df_raw[["store_nbr", "date"]].rename(
        columns={"date": "event_timestamp"}
    )
    entity_df = entity_df.copy()
    entity_df["event_timestamp"] = pd.to_datetime(entity_df["event_timestamp"])
    entity_df["store_nbr"] = entity_df["store_nbr"].astype(int)

    feature_df = store.get_historical_features(
        entity_df=entity_df,
        features=[
            "demand_features:onpromotion",
            "demand_features:day_of_week",
            "demand_features:month",
            "demand_features:year",
            "demand_features:days_to_holiday",
            "demand_features:lag_7",
            "demand_features:lag_14",
            "demand_features:rolling_mean_7",
            "demand_features:family",
            "demand_features:sales",
        ],
    ).to_df()

    # Sort chronologically to match the original split logic
    feature_df = feature_df.sort_values("event_timestamp").reset_index(drop=True)
    y = feature_df["sales"].values
    feature_df = feature_df.drop(columns=["event_timestamp", "store_nbr", "sales"])

    feature_df, encoder = encode_categoricals(feature_df, fit=True)
    return feature_df, encoder, y


def build_features_direct(df_raw: pd.DataFrame) -> tuple[pd.DataFrame, object]:
    """Apply feature engineering directly (no Feast). Original code path."""
    from training.features import (
        add_lag_features,
        add_rolling_features,
        extract_date_features,
    )

    df = df_raw.sort_values("date").reset_index(drop=True)
    df = extract_date_features(df)
    df = add_lag_features(df)
    df = add_rolling_features(df)
    df, encoder = encode_categoricals(df, fit=True)

    drop_cols = [c for c in ["date", "sales"] if c in df.columns]
    df = df.drop(columns=drop_cols)
    return df, encoder


def _fit_and_evaluate(
    model: lgb.LGBMRegressor,
    X_train: pd.DataFrame,
    y_train: np.ndarray,
    X_val: pd.DataFrame,
    y_val: np.ndarray,
) -> tuple[lgb.LGBMRegressor, float, float]:
    model.fit(
        X_train,
        y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(50, verbose=False), lgb.log_evaluation(-1)],
    )
    train_rmse = float(np.sqrt(mean_squared_error(y_train, model.predict(X_train))))
    val_rmse = float(np.sqrt(mean_squared_error(y_val, model.predict(X_val))))
    return model, train_rmse, val_rmse


def train(
    data_path: str = DEFAULT_DATA_PATH,
    use_optuna: bool = False,
    register_as_staging: bool = False,
) -> None:
    """Full training pipeline: load → features → split → fit → evaluate → save."""
    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    mlflow.set_experiment(EXPERIMENT_NAME)

    df_raw = load_data(data_path)

    # Feature retrieval: Feast when parquet exists, direct functions otherwise.
    feast_parquet = os.path.join(_REPO_ROOT, "data", "demand_features.parquet")
    if os.path.exists(feast_parquet):
        logger.info("Using Feast offline store for feature retrieval")
        X, encoder, y = build_features_feast(df_raw)
    else:
        logger.info(
            "demand_features.parquet not found — using direct feature functions. "
            "Run `python feature_repo/features.py` to enable Feast retrieval."
        )
        target = df_raw["sales"].values
        X, encoder = build_features_direct(df_raw)
        y = target

    logger.info("Feature matrix shape: %s", X.shape)

    split_idx = int(len(X) * TRAIN_RATIO)
    X_train, X_val = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_val = y[:split_idx], y[split_idx:]
    logger.info("Split: %d train rows / %d val rows", len(X_train), len(X_val))

    with mlflow.start_run() as run:
        run_id = run.info.run_id

        if use_optuna:
            import optuna

            optuna.logging.set_verbosity(optuna.logging.WARNING)

            def objective(trial: optuna.Trial) -> float:
                params = {
                    **MODEL_PARAMS,
                    "num_leaves": trial.suggest_int("num_leaves", 8, 64),
                    "learning_rate": trial.suggest_float(
                        "learning_rate", 0.01, 0.3, log=True
                    ),
                    "n_estimators": trial.suggest_int("n_estimators", 100, 800),
                }
                with mlflow.start_run(nested=True):
                    mlflow.log_params(
                        {
                            k: params[k]
                            for k in ("num_leaves", "learning_rate", "n_estimators")
                        }
                    )
                    m = lgb.LGBMRegressor(**params)
                    _, _, trial_val_rmse = _fit_and_evaluate(
                        m, X_train, y_train, X_val, y_val
                    )
                    mlflow.log_metric("val_rmse", trial_val_rmse)
                return trial_val_rmse

            study = optuna.create_study(direction="minimize")
            study.optimize(objective, n_trials=20)

            best = study.best_params
            logger.info("Best Optuna params: %s", best)
            final_params = {**MODEL_PARAMS, **best}
        else:
            final_params = MODEL_PARAMS

        model = lgb.LGBMRegressor(**final_params)
        model, train_rmse, val_rmse = _fit_and_evaluate(
            model, X_train, y_train, X_val, y_val
        )
        print(f"Train RMSE: {train_rmse:.4f}")
        print(f"Val   RMSE: {val_rmse:.4f}")

        log_params = {k: final_params[k] for k in ("num_leaves", "n_estimators")}
        log_params["learning_rate"] = final_params.get(
            "learning_rate", MODEL_PARAMS.get("learning_rate", "N/A")
        )
        mlflow.log_params(log_params)
        mlflow.log_metric("val_rmse", val_rmse)
        mlflow.log_metric("train_rmse", train_rmse)

        payload = {"model": model, "encoder": encoder}
        joblib.dump(payload, OUTPUT_MODEL_PATH)
        logger.info("Model saved to '%s'", OUTPUT_MODEL_PATH)

        mlflow.log_artifact(OUTPUT_MODEL_PATH, artifact_path="model")
        logger.info("Artifact logged to MLflow run %s", run_id)

    if register_as_staging:
        client = MlflowClient(tracking_uri=MLFLOW_TRACKING_URI)
        result = mlflow.register_model(
            model_uri=f"runs:/{run_id}/model/model.pkl",
            name=MODEL_REGISTRY_NAME,
        )
        client.transition_model_version_stage(
            name=MODEL_REGISTRY_NAME,
            version=result.version,
            stage="Staging",
        )
        logger.info(
            "Registered version %s as Staging in MLflow Registry", result.version
        )


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="Train LightGBM demand forecasting model"
    )
    parser.add_argument(
        "--data-path",
        default=DEFAULT_DATA_PATH,
        help="Path to Kaggle Store Sales train.csv",
    )
    parser.add_argument(
        "--use-optuna",
        action="store_true",
        default=False,
        help="Run Optuna hyperparameter search (~20 trials) instead of single run",
    )
    parser.add_argument(
        "--register-as-staging",
        action="store_true",
        default=False,
        help="Register the trained model to MLflow Registry as Staging",
    )
    args = parser.parse_args()
    train(
        data_path=args.data_path,
        use_optuna=args.use_optuna,
        register_as_staging=args.register_as_staging,
    )


if __name__ == "__main__":
    main()
