"""Feast feature definitions for mlops-loop demand forecasting.

Defines one Entity (store) and one FeatureView (demand_features) sourcing
from a Parquet offline store.  The feature transforms are performed by
training/features.py — this file is the Feast schema layer on top.

Materialization:
    python feature_repo/features.py
        Reads data/train.csv, applies transforms from training/features.py,
        writes data/demand_features.parquet for the FileSource below.
"""

from __future__ import annotations

import os
from datetime import timedelta

from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float64, Int64, String

# ---------------------------------------------------------------------------
# Offline store source — generated by the __main__ block below
# ---------------------------------------------------------------------------

_PARQUET_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "demand_features.parquet",
)

demand_source = FileSource(
    path=_PARQUET_PATH,
    timestamp_field="event_timestamp",
)

# ---------------------------------------------------------------------------
# Entity
# ---------------------------------------------------------------------------

store = Entity(
    name="store",
    join_keys=["store_nbr"],
    description="Retail store identifier (Kaggle Store Sales store_nbr)",
)

# ---------------------------------------------------------------------------
# FeatureView
# ---------------------------------------------------------------------------

demand_features = FeatureView(
    name="demand_features",
    entities=[store],
    ttl=timedelta(days=365 * 10),  # large TTL — dataset spans several years
    schema=[
        Field(name="onpromotion", dtype=Int64),
        Field(name="day_of_week", dtype=Int64),
        Field(name="month", dtype=Int64),
        Field(name="year", dtype=Int64),
        Field(name="days_to_holiday", dtype=Int64),
        Field(name="lag_7", dtype=Float64),
        Field(name="lag_14", dtype=Float64),
        Field(name="rolling_mean_7", dtype=Float64),
        Field(name="family", dtype=String),
        Field(name="sales", dtype=Float64),
    ],
    source=demand_source,
)

# ---------------------------------------------------------------------------
# Materialization script — run this before using Feast in train.py
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    import pandas as pd

    # Resolve paths relative to repo root (one level above feature_repo/)
    _REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    _SERVICE_DIR = os.path.join(_REPO_ROOT, "services", "forecast-api")
    if _SERVICE_DIR not in sys.path:
        sys.path.insert(0, _SERVICE_DIR)

    from training.features import (
        add_lag_features,
        add_rolling_features,
        extract_date_features,
    )

    data_path = os.path.join(_REPO_ROOT, "data", "train.csv")
    out_path = os.path.join(_REPO_ROOT, "data", "demand_features.parquet")

    print(f"Reading {data_path}")
    df = pd.read_csv(data_path, parse_dates=["date"])
    df = df.sort_values("date").reset_index(drop=True)

    df = extract_date_features(df)
    df = add_lag_features(df)
    df = add_rolling_features(df)

    df["event_timestamp"] = pd.to_datetime(df["date"])

    keep = [
        "store_nbr",
        "event_timestamp",
        "family",
        "onpromotion",
        "day_of_week",
        "month",
        "year",
        "days_to_holiday",
        "lag_7",
        "lag_14",
        "rolling_mean_7",
        "sales",
    ]
    df[keep].to_parquet(out_path, index=False)
    print(f"Written {len(df):,} rows to {out_path}")
